{
 "title": "Sync Trace",
 "tags": [ "nuodb" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "db",
    "query": "select distinct(\"dbname\") from (select first(numStalls) from \"nuodb_synctrace\" where $timeFilter GROUP BY \"dbname\")"
   },
   {
    "name": "host",
    "label": "host",
    "query": "select distinct(\"host\") from (select first(numStalls) from \"nuodb_synctrace\" where $timeFilter AND dbname =~ /^$database$/ GROUP BY \"host\")"
   },
   {
    "name": "nodes",
    "label": "node",
    "query": "select distinct(\"id\") from (select first(numStalls) from \"nuodb_synctrace\" where $timeFilter AND \"host\" =~ /^$host$/ AND \"dbname\" =~ /^$database$/ GROUP BY \"id\")"
   },
   {
    "name": "metric",
    "label": "metrics",
    "query": "SHOW TAG VALUES  FROM \"nuodb_synctrace\" WITH KEY = \"sync_trace_metric\" WHERE \"dbname\" =~ /^$database$/"
   },
   { "name": "percent", "label": "percentage greater than", "query": "0,0.01,0.05,.1,.2,.25,.3,.4,.5" }
  ]
 },
 "panels": [
  { "title": "Node $nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nodes" },
  {
   "title": "Total Stall Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "repeat": "listeners",
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "$tag_sync_trace_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sync_trace_metric" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_synctrace",
     "query": "SELECT LAST(M) FROM (SELECT mean(\"totalTimeStalls\") AS M, mean(\"totalSumStalls\") AS S FROM \"nuodb_synctrace\" WHERE (\"sync_trace_metric\" =~ /^$metric$/ AND  \"id\" =~ /^$nodes$/ AND \"host\" =~ /^$host$/ AND \"dbname\" =~ /^$database$/ ) AND $timeFilter GROUP BY time($__interval), \"sync_trace_metric\" fill(null)) WHERE $timeFilter AND M/S > $percent GROUP BY time($__interval),\"sync_trace_metric\" fill(null)",
     "select": [
      [
       { "params": [ "totalTimeStalls" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Stalls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sync_trace_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sync_trace_metric" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_synctrace",
     "query": "SELECT LAST(N) FROM (SELECT mean(\"totalTimeStalls\") AS M, mean(\"numStalls\") AS N, mean(\"totalSumStalls\") AS S FROM \"nuodb_synctrace\" WHERE (\"sync_trace_metric\" =~ /^$metric$/ AND \"host\" =~ /^$host$/ AND  \"id\" =~ /^$nodes$/ AND \"dbname\" =~ /^$database$/ ) AND $timeFilter GROUP BY time($__interval), \"sync_trace_metric\" fill(null)) WHERE $timeFilter AND M/S > $percent GROUP BY time($__interval),\"sync_trace_metric\" fill(null)",
     "select": [
      [
       { "params": [ "totalTimeStalls" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Stall Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "$tag_sync_trace_metric",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sync_trace_metric" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nuodb_synctrace",
     "query": "SELECT LAST(M)/LAST(N) FROM (SELECT mean(\"totalTimeStalls\") AS M, mean(\"numStalls\") AS N,  mean(\"totalSumStalls\") AS S FROM \"nuodb_synctrace\" WHERE (\"sync_trace_metric\" =~ /^$metric$/ AND  \"id\" =~ /^$nodes$/ AND \"host\" =~ /^$host$/ AND \"dbname\" =~ /^$database$/ ) AND $timeFilter GROUP BY time($__interval), \"sync_trace_metric\" fill(null)) WHERE $timeFilter AND M/S > $percent GROUP BY time($__interval),\"sync_trace_metric\" fill(null)",
     "select": [
      [
       { "params": [ "totalTimeStalls" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  }
 ]
}