{
 "title": "Communication",
 "tags": [
  "nuodb",
  "network"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "sent",
    "label": "Sent",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"nodetype\""
   },
   {
    "name": "received",
    "label": "Received",
    "query": "SHOW TAG VALUES FROM \"Milliseconds\" WITH KEY = \"nodetype\""
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")\n"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ GROUP BY \"host\")\n"
   }
  ]
 },
 "panels": [
  { "title": "Latest (1 minute) Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<h4 style=\"text-align:right;\">Sent</h4>"
   }
  },
  {
   "title": "TE",
   "type": "singlestat",
   "description": "Average data rate of messages sent by all selected TEs over the last minute interval for the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8  FROM \"BytesSent\" WHERE \"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time >= ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SM",
   "type": "singlestat",
   "description": "Average data rate of messages sent by all selected SMs over the last minute interval for the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8 FROM \"BytesSent\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": {
    "content": "<h4 style=\"text-align:right\">Received</h4>"
   }
  },
  {
   "title": "TE",
   "type": "singlestat",
   "description": "Average data rate of messages received by all selected TEs over the last minute interval for the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8 FROM \"BytesReceived\" WHERE \"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SM",
   "type": "singlestat",
   "description": "Average data rate of messages received by all selected SMs over the last minute interval for the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8 FROM \"BytesReceived\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Data Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sent Rate",
   "type": "graph",
   "description": "Message data rate sent by engine type per host averaged over the time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8 AS TE FROM \"BytesSent\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$sent$/ AND \"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8 AS SM FROM \"BytesSent\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$sent$/ AND \"nodetype\" = 'Storage' AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Rate",
   "type": "graph",
   "description": "Message data rate received by engine type per host averaged over the time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8 AS TE FROM \"BytesReceived\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$received$/ AND \"nodetype\" = 'Transaction'  AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\")*8 AS SM FROM \"BytesReceived\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$received$/ AND \"nodetype\" = 'Storage'  AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Message Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Sent Rate",
   "type": "graph",
   "description": "Count of messages sent by engine type per host averaged over the time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") AS TE  FROM \"MessagesSent\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$sent$/ AND \"nodetype\" = 'Transaction'  AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") AS SM FROM \"MessagesSent\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$sent$/ AND \"nodetype\" = 'Storage'  AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Rate",
   "type": "graph",
   "description": "Count of messages received by engine type per host averaged over the time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") AS TE FROM \"MessagesReceived\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$received$/ AND \"nodetype\" = 'Transaction'  AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col(host: $tag_host, db: $tag_db, nodeid: $tag_nodeid,  startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") AS SM FROM \"MessagesReceived\" WHERE (\"host\" =~ /^$host$/ AND \"nodetype\" =~ /^$received$/ AND \"nodetype\" = 'Storage'  AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}