{
 "title": "Disk",
 "tags": [
  "nuodb",
  "disk"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Storage' GROUP BY \"host\")\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest (1 minute) Archive Stats Averaged Over All SMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saves/sec",
   "type": "singlestat",
   "description": "Average (across all selected SMs) atom files saved per second for the last 1 minute of the current time window.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsSaved",
     "query": "SELECT mean(\"rate\")  FROM \"ObjectsSaved\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time >= ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "singlestat",
   "description": "Average (across all selected SMs) archive queue depth for the last 1 minute of the current time window.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveQueue",
     "query": "SELECT mean(\"raw\")  FROM \"ArchiveQueue\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Loaded/sec",
   "type": "singlestat",
   "description": "Average (across all selected SMs) number of atom files loaded into SM memory for the last 1 minute of the current time window.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObjectsLoaded",
     "query": "SELECT mean(\"rate\")  FROM \"ObjectsLoaded\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "FSync",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent file syncing atom files to the archive for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveFsyncTime",
     "query": "SELECT mean(\"value\")  FROM \"ArchiveFsyncTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Directory",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent in a directory operation (open/close/rename) within the archive for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveDirectoryTime",
     "query": "SELECT mean(\"value\")  FROM \"ArchiveDirectoryTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent in a write operation to the archive for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_  .",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveWriteTime",
     "query": "SELECT mean(\"value\")  FROM \"ArchiveWriteTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Read",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent in a read operation from the archive for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")  FROM \"ArchiveReadTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sync Throttle",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent throttling sync operations in the archive to allow other work to be performed for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")  FROM \"ArchiveSyncThrottleTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth Throttle",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent throttling write operations in the archive to allow read operations to be performed from the archive for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveBandwidthThrottleTime",
     "query": "SELECT mean(\"value\")  FROM \"ArchiveBandwidthThrottleTime\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time > ${__to}ms - 1m  and time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "singlestat",
   "description": "Average (across all selected SMs) rate of number of bytes written to the archive per second for the last 1 minute of the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ArchiveBufferedBytes",
     "query": "SELECT mean(\"rate\")  AS A FROM \"DiskWritten\" WHERE \"nodetype\" = 'Storage' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/  AND time >= ${__to}ms - 1m  and time < ${__to}ms",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "Archive Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Objects Saved / Read",
   "type": "graph",
   "description": "Above the x axis shows total number of  objects (atoms) saved averaged for each interval over the current time window.   Objects(atoms) read are shown below the x-axis.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):saved",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") AS M FROM \"ObjectsSaved\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "ObjectsLoaded",
     "query": "SELECT mean(\"rate\") AS M FROM \"ObjectsLoaded\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "FSync / Directory",
   "type": "graph",
   "description": "Above the x-axis shows percentage of time spent in file sync operation for each SM.  Below the x-axis shows percentage of time spent in directory (open/close/rename) operation. <BR/><BR/> <B><I>The maximum time spent in all I/O operations is 100% * number of archive threads.</I></B>",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):fsync",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS M FROM \"ArchiveFsyncTime\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):directory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS M FROM \"ArchiveDirectoryTime\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "description": "The left y-axis shows number of objects in archive queue.  The archive queue is composed of objects that have been modified and need to be written to the archive.  The right y-axis (and graphed in red) gives an indication of the amount of write throttling occurring.  Write throttling is done by the TE when the rate of object changes exceeds the rate at which the objects can be written to the archive.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):queuedepth",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"raw\") AS M FROM \"ArchiveQueue\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_db:writethrottle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS M FROM \"WriteThrottleTime\" WHERE \"host\" =~ /^$host$/ AND  \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval),  \"db\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Written / Sec",
   "type": "graph",
   "description": "The amount of data written to each selected archive per second.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rate\") AS M FROM \"DiskWritten\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest (1 minute) Journal Stats Averaged Over All SMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Sync",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent syncing journal messages to the journal for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalFsyncTime",
     "query": "SELECT mean(\"value\")  AS A FROM \"JournalFsyncTime\" WHERE \"nodetype\" = 'Storage' AND time >= ${__to}ms-1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Directory",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent in direcroty operations (open/close/delete) within the journal for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalDirectoryTime",
     "query": "SELECT mean(\"value\")  AS A FROM \"JournalDirectoryTime\" WHERE \"nodetype\" = 'Storage' AND time >= ${__to}ms-1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent writing journal messages to the journal for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalWriteTime",
     "query": "SELECT mean(\"value\")  AS A FROM \"JournalWriteTime\" WHERE \"nodetype\" = 'Storage' AND time >= ${__to}ms-1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Read",
   "type": "singlestat",
   "description": "Average (across all selected SMs) percentage of wallclock time spent reading from the journal for the last 1 minute of the current time window.  Max value would be _number archive threads * 100%_ .",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalWriteTime",
     "query": "SELECT mean(\"value\")  AS A FROM \"JournalReadTime\" WHERE \"nodetype\" = 'Storage' AND time >= ${__to}ms-1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "singlestat",
   "description": "Average (across all selected SMs) number of journal messages waiting to be added to journal over the last 1 minute sampled about every 10 seconds of the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JournalQueue",
     "query": "SELECT mean(\"raw\")  AS A FROM \"JournalQueue\" WHERE \"nodetype\" = 'Storage' AND time >= ${__to}ms-1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "singlestat",
   "description": "Average (across all selected SMs) rate of number of bytes written to the journal per second for the last 1 minute of the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JrnlBytes",
     "query": "SELECT mean(\"rate\")  AS A FROM \"JrnlBytes\" WHERE \"nodetype\" = 'Storage' AND time >= ${__to}ms-1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Writes",
   "type": "singlestat",
   "description": "Average (across all selected SMs) number of writes per second to the journal for the last 1 minute of the current time window.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "JrnlWrites",
     "query": "SELECT mean(\"rate\")  AS A FROM \"JrnlWrites\" WHERE \"nodetype\" = 'Storage' AND time >= ${__to}ms-1m AND time <= ${__to}ms",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  { "title": "Journal Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Queue",
   "type": "graph",
   "description": "Current number of messages in the journal queue yet to be added to the journal file.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"raw\") AS queuedepth FROM \"JournalQueue\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fsync / Directory",
   "type": "graph",
   "description": "Above the x-axis shows percentage of time spent in file sync'ng the journal for each SM.  Below the x-axis shows percentage of time spent in directory (open/close/rename) operation on the journal for  each SM. <BR/><BR/> <B><I>The maximum time spent in all I/O operations is 100%.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")*100 AS sync FROM \"JournalFsyncTime\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")*100 AS directory FROM \"JournalDirectoryTime\" WHERE \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ AND  (\"nodetype\" = 'Storage') AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Writes / Sec",
   "type": "graph",
   "description": "Rate at which messages are being written to the journal for each SM.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "JrnlBytes",
     "query": "SELECT mean(\"rate\") AS rate FROM \"JrnlWrites\" WHERE (\"nodetype\" = 'Storage' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  },
  {
   "title": "Bytes / Sec",
   "type": "graph",
   "description": "Throughput measured in bytes per second written to the journal for each SM.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host(db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid):$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "JrnlBytes",
     "query": "SELECT mean(\"rate\") AS throughput FROM \"JrnlBytes\" WHERE (\"nodetype\" = 'Storage' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"db\", \"nodeid\", \"startid\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Storage" }
     ]
    }
   ]
  }
 ]
}