{
 "title": "NuoDB Overview",
 "description": "NuoDB Summary",
 "tags": [ "overview" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")\n"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Transaction' GROUP BY \"host\")\n"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summary",
   "type": "graph",
   "description": "The left y-axis is for the stack bar graph that shows relative (in terms of cores) breakdown of where processing time is being spent.  The right y-axis and grey shadow area graph is an indication of the total number of cores available by all selected TEs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "measurement relative to vCPU" }
   ],
   "targets": [
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(nthreads) as \"nthreads\" FROM (SELECT mean(raw) / 10000. as \"nthreads\" FROM \"Summary.Fetch\",\"Summary.Commit\",\"Summary.Sync\",\"Summary.Lock\",\"Summary.NtwkSend\",\"Summary.Throttle\",\"Summary.CPU\" WHERE $timeFilter AND nodetype = 'Transaction' AND host =~ /^$host$/ AND db =~ /^$database$/ GROUP BY time($__interval), \"pid\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NumberCores",
     "query": "SELECT sum(ncores) FROM (SELECT mean(\"raw\") as ncores FROM \"NumberCores\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/ AND \"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"startid\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "the green line is relative to the left y-axis and displays the number of transactions committed per second.  Displayed below the x-axis relative to the right axis is an average (across all TEs) of the current number of transactions for the database at the time the metric was collected.   This measurement is a sum for the database as understood by the selected TEs.  At any point of time the understanding of which transactions are active will be slightly different in each TE.  The blue line is a calculation of the average number of transactions that were processing within the database for the colletion window (averaged across the display time window).   The data used to calculate this is collected only when a transaction is done processing.  So a transaction / statement that is in the database for a significant amount of time (for each a count on a very large table) will not skew this graph.  You'll see a big spike in the blue line when the long running statement ends.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "commits",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Commits",
     "query": "SELECT SUM( A ) FROM (SELECT mean(\"rate\")  AS A FROM \"Commits\" WHERE \"nodetype\" = 'Transaction' AND $timeFilter AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database/ GROUP BY \"startid\", time($interval) fill(null)) WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    },
    {
     "alias": "active:current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CurrentActiveTransactions",
     "query": "SELECT mean(\"raw\") FROM \"CurrentActiveTransactions\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"db\" fill(null)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "processing:average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "query": "SELECT SUM(X) FROM (SELECT mean(\"value\") as X FROM \"SqlListenerSqlProcTime\" WHERE (\"nodetype\" = 'Transaction') AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /$host$/) AND $timeFilter GROUP BY time($__interval), \"startid\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Workload",
   "type": "graph",
   "description": "How many transactions are Busy (in database) relative to Idle (not in database) during the collection interval. Only valid for NuoDB 4.1+",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Busy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "query": "SELECT SUM(X) FROM (SELECT mean(\"value\") AS X FROM \"SqlListenerSqlProcTime\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ ) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "query": "SELECT SUM(X) FROM (SELECT mean(\"value\") as X FROM \"SqlListenerIdleTransactionTime\" WHERE (\"nodetype\" = 'Transaction') AND (\"db\" =~ /^$database$/) AND (\"host\" =~ /$host$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)) WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  }
 ]
}