{
 "title": "SQL",
 "tags": [
  "nuodb",
  "sql"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "select distinct(\"db\") from (select first(raw) from \"Milliseconds\" where $timeFilter GROUP BY \"db\")"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "select distinct(\"host\") from (select first(raw) from \"Milliseconds\" where $timeFilter AND db =~ /$database$/ AND nodetype = 'Transaction' GROUP BY \"host\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Totals (averaged over last minute)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Commits/sec",
   "type": "singlestat",
   "description": "Aggregate sum of average commits per second for each TE in the most recent one minute interval of the current displayed time window.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Commits",
     "query": "SELECT SUM(a) FROM (SELECT mean(\"rate\") as a FROM \"Commits\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND time > ${__to}ms - 1m AND time <= ${__to}ms GROUP BY \"host\",\"pid\" )",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Rollbacks/sec",
   "type": "singlestat",
   "description": "Aggregate sum of average rollbacks per second for each TE in the most recent one minute interval of the current displayed time window.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Rollbacks",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"Rollbacks\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND time > ${__to}ms - 1m AND time <= ${__to}ms GROUP BY \"host\",\"pid\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "description": "Aggregate sum of the average number of client connections in the most recent one minute interval of the current displayed time window.",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ClientCncts",
     "query": "SELECT sum(a) FROM (SELECT mean(\"raw\") as a FROM \"ClientCncts\" WHERE ( \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/ ) AND time >= ${__to}ms - 1m and time < ${__to}ms GROUP BY \"host\",\"pid\")",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Row Updates/sec",
   "type": "singlestat",
   "description": "Aggregate sum of average number of rows updated per second for each TE in the most recent one minute interval of the current displayed time window.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Updates",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"Updates\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND time >= ${__to}ms - 1m AND time < ${__to}ms GROUP BY \"host\",\"pid\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Deletes/sec",
   "type": "singlestat",
   "description": "Aggregate sum of average number of rows deleted per second for each TE in the most recent one minute interval of the current displayed time window.",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Deletes",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"Deletes\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND time >= ${__to}ms - 1m AND time < ${__to}ms GROUP BY \"host\",\"pid\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  {
   "title": "Insert/sec",
   "type": "singlestat",
   "description": "Aggregate sum of average number of rows inserted per second for each TE in the most recent one minute interval of the current displayed time window.",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Inserts",
     "query": "SELECT sum(a) FROM (SELECT mean(\"rate\") as a FROM \"Inserts\" WHERE (\"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND time >= ${__to}ms - 1m AND time < ${__to}ms GROUP BY \"host\",\"pid\")",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Connections",
   "type": "graph",
   "description": "the number of SQL connections established with each selected TE at the time the metric is collected.  The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ClientCncts",
     "query": "SELECT mean(\"raw\") AS raw FROM \"ClientCncts\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\" , \"pid\" fill(null)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "This graph shows the average number of SQL connections executing within the database for the collection interval.   This is displayed per TE.   The value is calculated as SqlListenerSqlProcTime/Milliseconds  * 1000.  Since the value SqlListenerSqlProcTime is only incremented after a thread completes the transaction,  a long running sql statement will skew these numbers and large spikes will be noticed in the graph. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SqlListenerSqlProcTime",
     "query": "SELECT sum(\"value\") FROM \"SqlListenerIdleTime\" WHERE (\"nodetype\" = 'Transaction') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Commits",
   "type": "graph",
   "description": "Average number of commits per seconds within each selected TE. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Commits",
     "query": "SELECT mean(\"rate\") AS rate FROM \"Commits\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\" , \"pid\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "graph",
   "description": "Average number of rollbacks per second within each selected TE. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Rollbacks",
     "query": "SELECT mean(\"rate\") FROM \"Rollbacks\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Rows Inserted",
   "type": "graph",
   "description": "Average number of rows inserted  per second for each selected TE. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Inserts",
     "query": "SELECT mean(\"rate\") AS rate FROM \"Inserts\" WHERE (\"nodetype\" = 'Transaction' AND \"host\" =~ /^$host$/ AND \"db\" =~ /^$database$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Rows Updates",
   "type": "graph",
   "description": "Average number of rows updated  per second for each selected TE. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Updates",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Rows Deleted",
   "type": "graph",
   "description": "Average number of rows deleted per second for each selected TE. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Deletes",
     "query": "SELECT mean(\"rate\") FROM \"Deletes\" WHERE (\"nodetype\" = 'Transaction' AND \"db\" =~ /^$database$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Operations Stalled", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number Inserts Pending",
   "type": "graph",
   "description": "The average number of active transactions that are in a pending insert wait as measured by wait time associated with pending insert relative to interval window.  Pending Insert Wait is when a TE is waiting for acknowledgement from chairman that an insert will not invalidate uniqueness constraint on unique indexes. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PendingInsertWaitTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" }
     ]
    }
   ]
  },
  {
   "title": "Number Update Pending",
   "type": "graph",
   "description": "The average number of active transactions that are in a pending update wait as measured by wait time associated with pending update relative to interval window.  Pending Updte Wait is when a TE is waiting for acknowledgement from chairman that an update does not conflict with other transactions. The graph is a stack graph so top line is the average sum across all selected TEs.  The hover tooltip will show the individual values.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host ( db: $tag_db, nodeid: $tag_nodeid, startid: $tag_startid )",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "db" ], "type": "tag" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "startid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PendingUpdateWaitTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "nodetype", "operator": "=", "value": "Transaction" },
      { "condition": "AND", "key": "db", "operator": "=~", "value": "/^$database$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}