version: '3'

networks:
  net:

services:
  nuoadmin1:
    image: $NUODB_IMAGE

    # profiles: [ "distributed" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    # Do NOT remove this env_file value!!
    env_file: .env

    environment:
      NUODB_DOMAIN_ENTRYPOINT: ${PEER_ADDRESS:-nuoadmin1}
    hostname: ${PEER_ADDRESS:-nuoadmin1}
    ports:
      - 48004-48005:48004-48005
      - 8888:8888
    volumes:
      - ./scripts/start-nuoadmin:/usr/local/scripts/start-nuoadmin
      - ./scripts/stop-nuodb:/usr/local/bin/stop-nuodb
    
    command: [ "/usr/local/scripts/start-nuoadmin" ]

  sm:
    image: $NUODB_IMAGE
    # profiles: [ "distributed" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    # Do NOT remove this env_file value!!
    env_file: .env

    environment:
      PEER_ADDRESS: ${PEER_ADDRESS:-nuoadmin1}
      NUOCMD_API_SERVER: ${PEER_ADDRESS:-nuoadmin1}:8888
      ARCHIVE_DIR: ${ARCHIVE_PATH:-/var/opt/nuodb/archive}
      DB_OPTIONS: "mem ${ENGINE_MEM:-1Gi} execution-engine ${SQL_ENGINE:-vee} ${ENGINE_OPTIONS:-}"
      STARTUP_TIMEOUT: ${STARTUP_TIMEOUT:-90}      
    hostname: sm1
    depends_on:
      - nuoadmin1
    volumes:
      - ./scripts:/usr/local/scripts
      - ./scripts/stop-nuodb:/usr/local/bin/stop-nuodb
      - ${IMPORT_LOCAL:-./empty-file}:${IMPORT_MOUNT:-/var/tmp/env}

    command: [ "/usr/local/scripts/start-nuosm" ]

  te1:
    image: $NUODB_IMAGE
    # profiles: [ "distributed" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    # Do NOT remove this env_file value!!
    env_file: .env

    environment:
      PEER_ADDRESS: ${PEER_ADDRESS:-nuoadmin1}
      NUOCMD_API_SERVER: ${PEER_ADDRESS:-nuoadmin1}:8888
      STARTUP_TIMEOUT: ${STARTUP_TIMEOUT:-90}
      EXTERNAL_ADDRESS: ${EXTERNAL_ADDRESS:-te1}
    hostname: te1
    depends_on:
      - nuoadmin1
      - sm
    ports:
      - 48006:48006
    volumes:
      - ./scripts/start-nuote:/usr/local/scripts/start-nuote
      - ./scripts/stop-nuodb:/usr/local/bin/stop-nuodb

    command: [ "/usr/local/scripts/start-nuote" ]

  te2:
    image: $NUODB_IMAGE
    profiles: [ "scale-te2" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    # Do NOT remove this env_file value!!
    env_file: .env

    environment:
      PEER_ADDRESS: ${PEER_ADDRESS:-nuoadmin1}
      NUOCMD_API_SERVER: ${PEER_ADDRESS:-nuoadmin1}:8888
      STARTUP_TIMEOUT: ${STARTUP_TIMEOUT:-90}
      EXTERNAL_ADDRESS: ${EXTERNAL_ADDRESS:-te2}
    hostname: te2

    ports:
      - 48007:48006
    volumes:
      - ./scripts/start-nuote:/usr/local/scripts/start-nuote
    
    command: [ "/usr/local/scripts/start-nuote" ]

  monolith:
    image: $NUODB_IMAGE
    profiles: [ "monolith" ]
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      net:

    # Do NOT remove this env_file value!!
    env_file: .env

    environment:
      PEER_ADDRESS: ${PEER_ADDRESS:-db}
      NUODB_DOMAIN_ENTRYPOINT: ${PEER_ADDRESS:-localhost}
      NUOCMD_API_SERVER: ${PEER_ADDRESS:-localhost}:8888
      STARTUP_TIMEOUT: ${STARTUP_TIMEOUT:-90}
      EXTERNAL_ADDRESS: ${EXTERNAL_ADDRESS:-localhost}
      ARCHIVE_DIR: ${ARCHIVE_PATH:-/var/opt/nuodb/archive}
      DB_OPTIONS: "mem ${ENGINE_MEM:-1Gi} execution-engine ${SQL_ENGINE:-vee} ${ENGINE_OPTIONS:-}"
    # hostname: ${PEER_ADDRESS:-db}
    ports:
      - :48004-48007
      - :8888
    volumes:
      - ./scripts:/usr/local/scripts
      - ./scripts/stop-nuodb:/usr/local/bin/stop-nuodb
      - ${IMPORT_LOCAL:-./empty-file}:${IMPORT_MOUNT:-/var/tmp/env}  

    command: [ "/usr/local/scripts/start-monolith" ]  

  influxdb:
    image: influxdb:1.8
    profiles: [ "insights" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:    

    # ports:
      # The API for InfluxDB is served on port 8086
      # - "8086:8086"
      # - "8082:8082"
    volumes:
      - ./conf/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

  nuocd-sm:
    image: nuodb/nuodb-collector:latest
    profiles: [ "insights" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    depends_on:
      - nuoadmin1
      - sm
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCD_HOSTNAME: sm1
    pid: 'service:sm'

  nuocd-te1:
    image: nuodb/nuodb-collector:latest
    profiles: [ "insights" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    depends_on:
      - nuoadmin1
      - te1
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCD_HOSTNAME: te1
    pid: 'service:te1'

  nuocd-te2:
    image: nuodb/nuodb-collector:latest
    profiles: [ "scale-te2" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    depends_on:
      - nuoadmin1
      - te2
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCD_HOSTNAME: te2
    pid: 'service:te2'
    
  grafana:
    image: grafana/grafana:7.5.4
    profiles: [ "insights" ]
    restart: ${RESTART_POLICY:-unless-stopped}

    networks:
      net:

    depends_on:
      - influxdb
    environment:
      INFLUX_HOST: influxdb
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"

  # ycsb-demo:
  #   image: nuodb/ycsb:latest
  #   networks:
  #     net:
  #   depends_on:
  #     - te1
  #   environment:
  #     PEER_ADDRESS: ${PEER_ADDRESS:-nuoadmin1}
  #     DB_NAME:
  #     DB_USER:
  #     DB_PASSWORD:
  #   command: ["/driver/startup.sh"]
