version: '3'

networks:
  instadb:

services:
  instadb:
    image: $NUODB_IMAGE
    # profiles: [ "instadb" ]
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      instadb:

    # Do NOT remove this env_file value!!
    env_file: .env

    environment:
      PEER_ADDRESS: localhost
      NUODB_DOMAIN_ENTRYPOINT: localhost
      NUOCMD_API_SERVER: localhost:8888
      STARTUP_TIMEOUT: ${STARTUP_TIMEOUT:-90}
      EXTERNAL_ADDRESS: ${EXTERNAL_ADDRESS:-localhost}
      ARCHIVE_DIR: ${ARCHIVE_PATH:-/var/opt/nuodb/archive}
      DB_OPTIONS: "mem ${ENGINE_MEM:-1Gi} execution-engine ${SQL_ENGINE:-vee} ${ENGINE_OPTIONS:-}"
    ports:
      - :48004-48006
      - :8888
    volumes:
      - ./scripts:/usr/local/scripts
      - ./scripts/stop-nuodb:/usr/local/bin/stop-nuodb
      - ${IMPORT_LOCAL:-./empty-file}:${IMPORT_MOUNT:-/var/tmp/env}  

    command: [ "/usr/local/scripts/start-monolith" ]


  # ycsb-demo:
  #   image: nuodb/ycsb:latest
  #   networks:
  #     net:
  #   depends_on:
  #     - te1
  #   environment:
  #     PEER_ADDRESS: ${PEER_ADDRESS:-nuoadmin1}
  #     DB_NAME:
  #     DB_USER:
  #     DB_PASSWORD:
  #   command: ["/driver/startup.sh"]
